apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifty-two-books-tracker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fifty-two-books-tracker
  template:
    metadata:
      labels:
        app: fifty-two-books-tracker
    spec:
      containers:
        - name: fifty-two-books-tracker
          image: 940482412360.dkr.ecr.eu-west-1.amazonaws.com/fifty-two-books-tracker
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: awsBucket
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: awsRegion
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accessKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretKey
---
apiVersion: v1
kind: Service
metadata:
  name: fifty-two-books-tracker
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fifty-two-books-tracker
  ports:
    - port: 80
      targetPort: 8080
